{'Columbia University': 'https://ror.org/00hj8s172',
 'Cornell University': 'https://ror.org/05bnh6r87',
 'Environmental Molecular Sciences Laboratory': 'https://ror.org/04rc0xn13',
 'Harvard University': 'https://ror.org/03vek6s52',
 'Johns Hopkins University': 'https://ror.org/00za53h95',
 'Massachusetts Institute of Technology': 'https://ror.org/042nb2s44',
 'National Institutes of Health': 'https://ror.org/01cwqze88',
 'Pacific Northwest National Laboratory': 'https://ror.org/05h992307',
 'Pennsylvania State University': 'https://ror.org/04p491231',
 'Stanford University': 'https://ror.org/00f54p054',
 'The Ohio State University': 'https://ror.org/00rs6vg23',
 'University of California, Berkeley': 'https://ror.org/01an7q238',
 'University of California, Davis': 'https://ror.org/05rrcem69',
 'University of California, Los Angeles': 'https://ror.org/046rm7j60',
 'University of California, San Diego': 'https://ror.org/0168r3w48',
 'University of California, San Francisco': 'https://ror.org/043mz5j54',
 'University of Florida': 'https://ror.org/02y3ad647',
 'University of Illinois Urbana-Champaign': 'https://ror.org/047426m28',
 'University of Michigan–Ann Arbor': 'https://ror.org/00jmfr291',
 'University of Minnesota': 'https://ror.org/017zqws13',
 'University of Pennsylvania': 'https://ror.org/00b30xv10',
 'University of Pittsburgh': 'https://ror.org/01an3r305',
 'University of Washington': 'https://ror.org/00cvxb145',
 'University of Wisconsin–Madison': 'https://ror.org/01y2jtd41',
 'Yale University': 'https://ror.org/03v76x132'}
